### ISSUE TITLE
MvvmDataGrid OverflowException with high, saved Column Width values

### ISSUE THREAD

**Issue by StackUnderflowException** [ActiveDevelop/MvvmForms#1]
Under unknown circumstances it can happen, that a value for a Column Width is saved, which can't be converted to the type DataGridLength when loaded. It results into an OverflowException. This Exception is not catched and crashes the whole software.

Note: The Value is in range of double, but can't be converted through the System.Windows.Controls.DataGridLengthConverter.ConvertFromString(str) method - it throws an OverflowException with the message "Value was either too large or too small for a Double".

**Comment by surgien** [comment]
07c3db3d36a9b4a409dae98c04ebfe30abdc85e7

**Comment by surgien** [comment]
07c3db3d36a9b4a409dae98c04ebfe30abdc85e7 #1
