### ISSUE TITLE
Nuget packages possible problem?

### ISSUE THREAD

**Issue by alprinias** [ActiveDevelop/MvvmForms#4]
Hi,
I'm trying to follow the procedure described in the wiki. However, although the package installs correctly (2.3,2-Beta) the 2 dlls are not found in my bin folder after building the solution, only one called ActiveDevelop.MvvmBaseLib.dll, which does not exhibit any components that can be added to the Toolbox. 

Any ideas?
Alex

**Comment by alprinias** [comment]
Ok, went and added by hand the missing dll from the location it had been downloaded into by nuget. 

Now, when I try to add a MvvmManager, I get an error saying "could not load file or assembly MvvmBaseLib.NetStandard..."

Alex

**Comment by KlausLoeffelmann** [comment]
Which .NET Framework are you targeting? 
I think we need 4.7 for 2.3.2 Beta. @surgien, can you give some advise?
(Will take some time, we're in GMT+1...)

**Comment by KlausLoeffelmann** [comment]
About the toolbox: You need to do a trick to populate them to the toolbox, since a NuGet cannot populate the toolbox, and we did not want a VSIX. (If you had a solution for that, we'd be HAPPY to hear about! :-) ). The Wiki describes how it is done.

**Comment by alprinias** [comment]
Thanks for the fast response!

I'm targeting 4.5.2.
I followed the Wiki, but as I said in my original post, I ended up not having the dlls in my bin folder after installing the nuget and building. 
Don't worry for delays, I'm in GMT+2.

**Comment by KlausLoeffelmann** [comment]
Since we decided to go for .NET Standard 2.0, I suppose 4.5.2 will not work (they're simply not compatible). If you cannot upgrade to 4.7 or 4.7.1, then you need to downgrade MvvmForms to 2.x (@surgien need to confirm the highest working Version), but you need to use PCLs then. (You could try to use the backwards compatibility setting for .NET Standard Dlls by inserting this 

```
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>
  </PropertyGroup>

```

into your project, but I personally did never test this, so I would not be able to say reliably, if that's really working. Target would then be .NET Standard 1.4, if I remember correctly.)

**Comment by alprinias** [comment]
Sooo, I installed 4.7.1 and created a new test project and it now works!
My problem now is that when I go to the MvvmManager and select "Manage View/ViewModel Bindings..." I get a pop up "Value cannot be null. Parameter name: collection" with an OK button. When I press the button, VS crashes and restarts itself.. this is VS 2015 Community.
Alex.

**Comment by surgien** [comment]
The DataContextType-Property is empty. You have to define a type first. Crash will be fixed.

**Comment by KlausLoeffelmann** [comment]
Can we issue a MessageBox-Box warning that the DataContextType-Property is not set, and not swallow silently?
